# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 18:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/avatars')),
                ('contract_rate', models.FloatField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'Agents',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_been_printed', models.BooleanField(default=False)),
                ('issuing_date', models.DateTimeField(auto_now_add=True, help_text='This will automatically be set when bond is printed', null=True)),
                ('amount', models.FloatField()),
                ('premium', models.FloatField()),
                ('related_court', models.CharField(max_length=50)),
                ('county', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('warrant_number', models.CharField(max_length=50)),
                ('offences', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('next_court_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('agents', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Powers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powers_type', models.CharField(choices=[('5000.00', '5000.00'), ('15000.00', '15000.00'), ('25000.00', '25000.00'), ('50000.00', '50000.00'), ('100000.00', '100000.00'), ('150000.00', '150000.00'), ('250000.00', '250000.00'), ('500000.00', '500000.00')], max_length=50)),
                ('start_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('end_date_field', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'powers',
            },
        ),
        migrations.CreateModel(
            name='SuretyCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('seal', models.ImageField(upload_to='static/%Y/%m/%d')),
                ('prefix', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Surety Companies',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('powers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='powers.Powers')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='powers',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='powers',
            name='surety_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.SuretyCompany'),
        ),
        migrations.AddField(
            model_name='bond',
            name='defendant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='powers.Defendant'),
        ),
        migrations.AddField(
            model_name='bond',
            name='powers',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='powers.Powers'),
        ),
    ]
