# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0002_auto_20180212_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transmission',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='transmission',
            name='powers',
        ),
        migrations.DeleteModel(
            name='Transmission',
        ),
    ]
