# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-10 16:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0004_auto_20180213_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='agents',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
