# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0005_auto_20180310_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powers',
            name='end_date_field',
            field=models.DateField(),
        ),
    ]
