# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0007_bond_bond_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='premium',
            field=models.FloatField(editable=False),
        ),
    ]
