# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0008_auto_20180312_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='voided',
            field=models.NullBooleanField(default=False),
        ),
    ]
