# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-13 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0009_bond_voided'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powers',
            name='end_date_field',
            field=models.DateField(editable=False),
        ),
    ]
