# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0010_auto_20180313_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='warrant_number',
            field=models.TextField(),
        ),
    ]
