# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-04 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0011_auto_20180328_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='powers',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bond_powers', to='powers.Powers'),
        ),
    ]
