# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-06 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0013_auto_20180604_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='issuing_date',
            field=models.DateTimeField(auto_now_add=True, help_text='This will automatically be set when bond is printed', null=True),
        ),
    ]
