# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-26 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0015_bond_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
    ]
