# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-03 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('powers', '0016_auto_20190626_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bond',
            old_name='offences',
            new_name='offenses')
    ]
