# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-09 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0018_user_powers_low_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='discharded_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bond',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Discharged', 'Discharged'), ('Dismissed', 'Dismissed'), ('FLTA', 'FLTA')], default='Pending', max_length=50),
        ),
    ]
