# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0019_auto_20190909_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='BondFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bond-files/%Y/%m/%d')),
                ('bond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='powers.Bond')),
            ],
        ),
    ]
