# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-09 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0020_bondfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bondfile',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
