# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-09 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0021_bondfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bondfile',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
