# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-11 12:59
from __future__ import unicode_literals

from django.db import migrations

def migrate_is_active(apps , schema_editor):
    Bond = apps.get_model('powers', 'Bond')
    for mm in Bond.objects.all():
        if not mm.is_active:
            mm.status = 'Discharged'
        mm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0022_auto_20190909_1548'),
    ]
    operations = [
        migrations.RunPython(migrate_is_active),

        migrations.RemoveField(
            model_name='bond',
            name='is_active',
        ),
    ]
