# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-10 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0023_remove_bond_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='powers',
            name='powers_type',
            field=models.CharField(choices=[('5000.00', '5000.00'), ('15000.00', '15000.00'), ('25000.00', '25000.00'), ('50000.00', '50000.00'), ('99000.00', '99000.00'), ('100000.00', '100000.00'), ('150000.00', '150000.00'), ('250000.00', '250000.00'), ('500000.00', '500000.00')], max_length=50),
        ),
    ]
