# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-10-10 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0024_auto_20191010_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='deleted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
