# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-22 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0025_auto_20191010_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='dischard_explanation',
            field=models.TextField(blank=True, help_text='Please provide explanation for discharging bond.', null=True),
        ),
    ]
