# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-07 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0025_auto_20191010_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='bot_error',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
