# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-12-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0026_bond_bot_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='bot_last_run',
            field=models.DateField(blank=True, null=True)
        ),
    ]
