# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-22 23:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0028_bond_times_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='discharded_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
