# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-22 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0032_auto_20200622_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bond',
            old_name='discharded_date',
            new_name='discharged_date',
        ),
    ]
