# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-07 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0034_auto_20200622_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='bond',
            name='post_date',
            field=models.BooleanField(default=False, help_text="If checked the bond's date will be set to tomorrow otherwise it will be set for today's date"),
        ),
    ]
